### ISSUE TITLE
TestLuceneDocumentIndexService Unit Test Failing

### ISSUE THREAD

**Issue by greg-v** [vmware/xenon#2]
Trying to build against commit: 6dcb4e2427d189426e1282a871249d8a6d985f6a
Run: mvn clean test
Produces unit test failure below.

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T09:41:47-07:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"

```
-------------------------------------------------------------------------------
Test set: com.vmware.dcp.services.common.TestLuceneDocumentIndexService
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.987 sec <<< FAILURE! - in com.vmware.dcp.services.common.TestLuceneDocumentIndexService
corruptIndexWhileRunning(com.vmware.dcp.services.common.TestLuceneDocumentIndexService)  Time elapsed: 0.148 sec  <<< ERROR!
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:718)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:732)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1359)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1142)
	at com.vmware.dcp.services.common.LuceneDocumentIndexService.addDocumentToIndex(LuceneDocumentIndexService.java:1670)
	at com.vmware.dcp.services.common.LuceneDocumentIndexService.handleDocumentPostOrDelete(LuceneDocumentIndexService.java:1274)
	at com.vmware.dcp.services.common.LuceneDocumentIndexService.lambda$handleRequest$158(LuceneDocumentIndexService.java:481)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schadr** [comment]
Interesting I just ran the same commit using a fresh clone and it worked, I'm running OSx 10.10.5 however.

**Comment by georgechrysanthakopoulos** [comment]
this test deletes files while the runtime is running, so filesyste / disk differences might expose some timing. It passes reliably in CI (linux and windows) and on my macbook pro.

is it 100% repro? all other index related test pass ok?

**Comment by greg-v** [comment]
Could very well be a timing issue.  I was able to build it successfully on a newer (presumably faster) MBP.  That system also has OS X 10.10.5 though, so could also be OS version related.

It is 100% reproducible.  Started from scratch: git clone https://github.com/vmware/xenon.git; cd xenon; mvn clean test

Same result.

**Comment by georgechrysanthakopoulos** [comment]
We have a consistent repro finally, pnoorduis is disabling test for now

**Comment by georgechrysanthakopoulos** [comment]
see this change:
https://github.com/vmware/xenon/commit/99e5122e28e6dcefbdc3697a5b75f89d2db4e1c4

Pieter was able to repro on his linux machine
